[project]
name = "deepreinforcementlearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gym>=0.26.2",
    "matplotlib>=3.10.1",
    "optuna>=4.2.1",
    "torch>=2.6.0",
]
